dataset: mot

train_split: mot16_train_coco
val_split: mot16_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: /home/dell/PK/DataSet/MOT16
mot_path_val: /home/dell/PK/DataSet/MOT16

resume: /home/dell/PK/trackformer/models/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_hidden_dim_288.pth

epochs: 60
lr_drop: 10