dataset: mot_crowdhuman

crowdhuman_train_split: train_val
train_split: mot17_train_coco
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: /home/cqjtu/PK/DataSet/MOT17
mot_path_val: /home/cqjtu/PK/DataSet/MOT17
crowdhuman_path: /home/cqjtu/PK/DataSet/CrowdHuman

resume: /home/cqjtu/PK/trackformer_1_cqjtu_41/models/crowdhuman_deformable_multi_frame/checkpoint_epoch_80.pth

epochs: 45
lr_drop: 10