dataset: mot_crowdhuman

crowdhuman_train_split: train_val
train_split: mot20_train_coco
val_split: mot20_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: /home/dell/PK/DataSet/MOT20
mot_path_val: /home/dell/PK/DataSet/MOT20
crowdhuman_path: /home/dell/PK/DataSet/CrowdHuman

resume: /home/dell/PK/trackformer_1_v45/models/checkpoint_epoch_80.pth

epochs: 55
lr_drop: 10